### ISSUE TITLE
video cache

### ISSUE THREAD

**Issue by kia1349** [MarcinMoskala/VideoPlayView#1]
Does it support the cache?

**Comment by MarcinMoskala** [comment]
It is using `VideoView` for movie display. I am not sure but I believe that is it supporting streaming and buffering. I think cache is in the view but it is destroyed when view is destroyed (in looping view is loaded once, but if you leave an app and open it again then movie will be downloaded again)

**Comment by kia1349** [comment]
thanks a lot
