### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by hafiz013** [MarcinMoskala/VideoPlayView#5]
1) Are this library can rotate when full screen?
2) Are this library can play video list in recycleview?
3) when scrolling and auto play

**Comment by MarcinMoskala** [comment]
1. Full screen? I believe it doesn't support rotation, but I think you can help us add this feature :)
2. Yes, I use it this way
3. Not sure.

**Comment by hafiz013** [comment]
hi this features how long you will implement it? simple like facebook video which are list video that has enlarge icon on bottom right corner (landscape) and shrink back (potrait). If i click one of those video goes to list scroll video that can auto play when visible to view

**Comment by MarcinMoskala** [comment]
I am not planning to implement it at all.
